### ISSUE TITLE
can i check the action kind

### ISSUE THREAD

**Issue by alexnest** [justinrubek/async-watcher#11]
Hi justinrubek.

In notify repository examples , it provides a demo output the action kind.For example,when i create a file , it shows "CREATE", when i update file ,  it shows "MODIFY".when i delete a file , it show "REMOVE".
Can you provide an example shows the action kind?

Thank you first.

**Comment by justinrubek** [comment]
This wasn't previously possible to do with this crate, but I think it is a good idea to add it. I've got a PR added which will add an `event` field to the `DebouncedEvent` struct, which is the notify event and can be used similarly. See #12 for the change.

I think it that change should be fine, but I'll wait a little bit before merging it in so I can be sure.

The `simple` example will now do some pretty-printing that showcases how to access event data.

**Comment by alexnest** [comment]
Wow,it works grate in my app.Thx a lot.
